"""make tables

Revision ID: e00066e78242
Revises: 
Create Date: 2024-05-07 11:45:33.193602

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e00066e78242'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musclegroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('punishment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('punishment_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('punishment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedual',
    sa.Column('sunday', sa.Integer(), nullable=False),
    sa.Column('monday', sa.Integer(), nullable=False),
    sa.Column('tuesday', sa.Integer(), nullable=False),
    sa.Column('wednesday', sa.Integer(), nullable=False),
    sa.Column('thursday', sa.Integer(), nullable=False),
    sa.Column('friday', sa.Integer(), nullable=False),
    sa.Column('satuday', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['friday'], ['musclegroup.id'], ),
    sa.ForeignKeyConstraint(['monday'], ['musclegroup.id'], ),
    sa.ForeignKeyConstraint(['satuday'], ['musclegroup.id'], ),
    sa.ForeignKeyConstraint(['sunday'], ['musclegroup.id'], ),
    sa.ForeignKeyConstraint(['thursday'], ['musclegroup.id'], ),
    sa.ForeignKeyConstraint(['tuesday'], ['musclegroup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wednesday'], ['musclegroup.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('set', sa.Integer(), nullable=False),
    sa.Column('rep', sa.Integer(), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['musclegroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout')
    op.drop_table('schedual')
    op.drop_table('user')
    op.drop_table('reward')
    op.drop_table('punishment')
    op.drop_table('musclegroup')
    # ### end Alembic commands ###
